enable-module-update = true # set this to false if you do not want to receive updates for the module
compression-level = 9
patches-version = "dev"
cli-version = "dev"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "both"
version = "20.21.37"
excluded-patches = "'Custom branding'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music]
build-mode = "both"
arch = "arm64-v8a"
excluded-patches = "'Custom branding'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[Instagram]
build-mode = "apk"
arch = "arm64-v8a"
version = "latest"
included-patches = "'Hide ads' 'Hide suggested content' 'Disable analytics' 'Remove build expired popup' 'Disable story auto flipping' 'Prevent screenshot detection' 'Remove screenshot restriction'"
exclusive-patches = true
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
